Repository mukgen/mukgen_BackEnd_V1, pull requests merged in 2023-05, with the labels that each got.

#5 🔀 :: feature/board to develop
  src/main/java/com/example/mukgen/domain/board/controller/BoardController.java
  src/main/java/com/example/mukgen/domain/board/controller/dto/response/BoardResponse.java
  src/main/java/com/example/mukgen/domain/board/entity/Board.java
  src/main/java/com/example/mukgen/domain/board/service/BoardService.java
  src/main/java/com/example/mukgen/domain/like/controller/LikesController.java
  src/main/java/com/example/mukgen/domain/like/controller/dto/request/LikeCreateRequest.java
  src/main/java/com/example/mukgen/domain/like/controller/dto/response/LikeResponse.java
  src/main/java/com/example/mukgen/domain/like/entity/Likes.java
  src/main/java/com/example/mukgen/domain/like/repository/LikeRepository.java
  src/main/java/com/example/mukgen/domain/like/service/LikeService.java
  src/main/resources/application.yml
Labels: 생성

#9 🔀 :: feature to develop
  src/main/java/com/example/mukgen/domain/auth/controller/AuthController.java
  src/main/java/com/example/mukgen/domain/auth/controller/request/UserModifyPasswordRequest.java
  src/main/java/com/example/mukgen/domain/auth/service/AuthService.java
  src/main/java/com/example/mukgen/domain/user/controller/UserController.java
  src/main/java/com/example/mukgen/domain/user/entity/User.java
  src/main/java/com/example/mukgen/domain/user/repository/UserRepository.java
Labels: 생성

#8 🔀 :: feature/refactoring to develop
  src/main/java/com/example/mukgen/domain/auth/controller/reponse/TokenResponse.java
  src/main/java/com/example/mukgen/domain/board/controller/BoardController.java
  src/main/java/com/example/mukgen/domain/board/controller/dto/request/BoardCreateRequest.java
  src/main/java/com/example/mukgen/domain/board/controller/dto/request/BoardUpdateRequest.java
  src/main/java/com/example/mukgen/domain/board/controller/dto/response/BoardResponse.java
  src/main/java/com/example/mukgen/domain/board/service/BoardService.java
  src/main/java/com/example/mukgen/domain/user/controller/UserController.java
  src/main/java/com/example/mukgen/domain/user/service/UserService.java
Labels: 리펙토링

#19 🔀 :: refactoring to develop
  src/main/resources/application.yml
Labels: 리펙토링

#18 🔀 :: feature/meal to develop
  build.gradle.kts
  src/main/java/com/example/mukgen/MukgenApplication.java
  src/main/java/com/example/mukgen/domain/meal/controller/MealController.java
  src/main/java/com/example/mukgen/domain/meal/entity/Rice.java
  src/main/java/com/example/mukgen/domain/meal/entity/RiceType.java
  src/main/java/com/example/mukgen/domain/meal/entity/dto/request/MealRequest.java
  src/main/java/com/example/mukgen/domain/meal/repository/MealRepository.java
  src/main/java/com/example/mukgen/domain/meal/service/MealApi.java
  src/main/java/com/example/mukgen/domain/meal/service/MealService.java
  src/main/java/com/example/mukgen/global/config/security/SecurityConfig.java
Labels: 생성

#31 🔀 :: refactoring to develop
  src/main/java/com/example/mukgen/domain/board/controller/BoardController.java
  src/main/java/com/example/mukgen/domain/board/controller/dto/response/BoardResponse.java
  src/main/java/com/example/mukgen/domain/board/service/BoardService.java
  src/main/java/com/example/mukgen/domain/like/controller/LikesController.java
  src/main/java/com/example/mukgen/domain/like/service/LikeService.java
  src/main/java/com/example/mukgen/domain/meal/controller/MealController.java
  src/main/java/com/example/mukgen/domain/meal/controller/dto/request/MealRequest.java
  src/main/java/com/example/mukgen/domain/meal/entity/Meal.java
  src/main/java/com/example/mukgen/domain/meal/entity/MealType.java
  src/main/java/com/example/mukgen/domain/meal/repository/MealRepository.java
  src/main/java/com/example/mukgen/domain/meal/service/MealApi.java
  src/main/java/com/example/mukgen/domain/meal/service/MealService.java
  src/main/java/com/example/mukgen/domain/review/controller/ReviewController.java
  src/main/java/com/example/mukgen/domain/review/entity/Review.java
  src/main/java/com/example/mukgen/domain/review/entity/dto/response/ReviewResponse.java
  src/main/java/com/example/mukgen/domain/review/repository/ReviewRepository.java
  src/main/java/com/example/mukgen/domain/review/service/ReviewService.java
  src/main/java/com/example/mukgen/domain/user/controller/response/UserProfileResponse.java
  src/main/java/com/example/mukgen/domain/user/service/UserService.java
Labels: 리펙토링

#36 🔀 :: feature/boardcomment to develop
  src/main/java/com/example/mukgen/domain/board/controller/dto/response/BoardResponse.java
  src/main/java/com/example/mukgen/domain/board/entity/Board.java
  src/main/java/com/example/mukgen/domain/boardcomment/controller/BoardCommentController.java
  src/main/java/com/example/mukgen/domain/boardcomment/controller/dto/request/BoardCommentCreateRequest.java
  src/main/java/com/example/mukgen/domain/boardcomment/controller/dto/request/BoardCommentUpdateRequest.java
  src/main/java/com/example/mukgen/domain/boardcomment/controller/dto/response/BoardCommentResponse.java
  src/main/java/com/example/mukgen/domain/boardcomment/entity/BoardComment.java
  src/main/java/com/example/mukgen/domain/boardcomment/repository/BoardCommentRepository.java
  src/main/java/com/example/mukgen/domain/boardcomment/service/BoardCommentService.java
  src/main/java/com/example/mukgen/domain/boardcomment/service/exception/BoardCommentNotFoundException.java
  src/main/java/com/example/mukgen/domain/boardcomment/service/exception/BoardCommentWriterMissMatchException.java
  src/main/java/com/example/mukgen/domain/review/controller/ReviewController.java
  src/main/java/com/example/mukgen/domain/review/controller/dto/request/ReviewCreateRequest.java
  src/main/java/com/example/mukgen/domain/review/controller/dto/response/ReviewResponse.java
  src/main/java/com/example/mukgen/domain/review/controller/dto/response/ReviewResponseList.java
  src/main/java/com/example/mukgen/domain/review/service/ReviewService.java
  src/main/java/com/example/mukgen/domain/review/service/exception/ReviewAlreadyExistsException.java
  src/main/java/com/example/mukgen/global/error/exception/ErrorCode.java
Labels: 생성

#39 🔀 :: feature/refactoring to develop
  src/main/java/com/example/mukgen/domain/auth/controller/request/UserLoginRequest.java
  src/main/java/com/example/mukgen/domain/auth/controller/request/UserSignupRequest.java
  src/main/java/com/example/mukgen/domain/auth/service/AuthService.java
Labels: 리펙토링

#41 🔀 :: feature/exception-handling to develop
  src/main/java/com/example/mukgen/domain/auth/controller/AuthController.java
  src/main/java/com/example/mukgen/domain/auth/controller/request/UserSignupRequest.java
  src/main/java/com/example/mukgen/global/error/GlobalExceptionHandler.java
Labels: 생성

#43 🔀 :: feature/refactoring to develop
  src/main/java/com/example/mukgen/domain/boardcomment/entity/BoardComment.java
  src/main/java/com/example/mukgen/domain/like/entity/Likes.java
  src/main/java/com/example/mukgen/domain/review/entity/Review.java
  src/main/java/com/example/mukgen/domain/rice/entity/Rice.java
  src/main/java/com/example/mukgen/global/error/GlobalExceptionHandler.java
Labels: 리펙토링

#44 🔀 :: feature/board to develop
  src/main/java/com/example/mukgen/domain/board/controller/BoardController.java
  src/main/java/com/example/mukgen/domain/board/service/BoardService.java
Labels: 수정

#45 🔀 :: feature/refactoring to develop
  src/main/java/com/example/mukgen/domain/board/controller/BoardController.java
  src/main/java/com/example/mukgen/domain/board/controller/dto/response/BoardListResponse.java
  src/main/java/com/example/mukgen/domain/board/controller/dto/response/BoardMaximumResponse.java
  src/main/java/com/example/mukgen/domain/board/controller/dto/response/BoardMinimumResponse.java
  src/main/java/com/example/mukgen/domain/board/entity/Board.java
  src/main/java/com/example/mukgen/domain/board/repository/BoardRepository.java
  src/main/java/com/example/mukgen/domain/board/service/BoardService.java
  src/main/java/com/example/mukgen/domain/boardcomment/service/BoardCommentService.java
  src/main/java/com/example/mukgen/domain/like/controller/dto/response/LikeResponse.java
  src/main/java/com/example/mukgen/domain/like/entity/Likes.java
  src/main/java/com/example/mukgen/domain/like/repository/LikeRepository.java
  src/main/java/com/example/mukgen/domain/user/entity/User.java
  src/main/java/com/example/mukgen/domain/user/repository/UserRepository.java
  src/main/java/com/example/mukgen/global/config/security/SecurityConfig.java
  src/main/java/com/example/mukgen/global/config/security/auth/CustomUserDetailService.java
  src/main/java/com/example/mukgen/global/config/security/auth/CustomUserDetails.java
Labels: 리펙토링

#46 🔀 :: feature/refactoring to develop
  src/main/java/com/example/mukgen/domain/board/controller/BoardController.java
  src/main/java/com/example/mukgen/domain/board/service/BoardService.java
Labels: 리펙토링

#57 🔀 :: feature/review to develop
  src/main/java/com/example/mukgen/domain/review/service/ReviewService.java
Labels: 생성

#56 🔀 :: feature/board to develop
  src/main/java/com/example/mukgen/domain/board/controller/BoardController.java
  src/main/java/com/example/mukgen/domain/board/controller/dto/response/BoardMaximumResponse.java
  src/main/java/com/example/mukgen/domain/board/controller/dto/response/BoardMinimumResponse.java
  src/main/java/com/example/mukgen/domain/board/controller/dto/response/BoardPopularListResponse.java
  src/main/java/com/example/mukgen/domain/board/controller/dto/response/BoardPopularResponse.java
  src/main/java/com/example/mukgen/domain/board/controller/dto/response/BoardTabListResponse.java
  src/main/java/com/example/mukgen/domain/board/entity/Board.java
  src/main/java/com/example/mukgen/domain/board/repository/BoardRepository.java
  src/main/java/com/example/mukgen/domain/board/service/BoardService.java
  src/main/java/com/example/mukgen/domain/review/service/ReviewService.java
Labels: 생성

#62 🔀 :: feature/board to develop
  src/main/java/com/example/mukgen/domain/board/controller/BoardController.java
  src/main/java/com/example/mukgen/domain/board/controller/dto/response/BoardMinimumResponse.java
  src/main/java/com/example/mukgen/domain/board/entity/Board.java
  src/main/java/com/example/mukgen/domain/board/repository/BoardRepository.java
  src/main/java/com/example/mukgen/domain/board/service/BoardService.java
Labels: 생성

#63 🔀 :: feature/soft-deleted to develop
  src/main/java/com/example/mukgen/domain/boardcomment/entity/BoardComment.java
  src/main/java/com/example/mukgen/domain/like/entity/Likes.java
  src/main/java/com/example/mukgen/domain/review/entity/Review.java
Labels: 생성

#66 🔀 :: feature/response-add-id to develop
  src/main/java/com/example/mukgen/domain/board/controller/dto/response/BoardMaximumResponse.java
  src/main/java/com/example/mukgen/domain/board/controller/dto/response/BoardMinimumResponse.java
  src/main/java/com/example/mukgen/domain/board/controller/dto/response/BoardPopularResponse.java
  src/main/java/com/example/mukgen/domain/boardcomment/service/BoardCommentService.java
  src/main/java/com/example/mukgen/domain/review/controller/dto/response/ReviewResponse.java
  src/main/java/com/example/mukgen/domain/review/service/ReviewService.java
  src/main/java/com/example/mukgen/domain/rice/controller/dto/response/RiceResponse.java
  src/main/java/com/example/mukgen/domain/rice/service/RiceService.java
Labels: 생성

#67 🔀 :: feature/find-my-entity to develop
  src/main/java/com/example/mukgen/domain/board/repository/BoardRepository.java
  src/main/java/com/example/mukgen/domain/board/service/BoardService.java
  src/main/java/com/example/mukgen/domain/review/controller/ReviewController.java
  src/main/java/com/example/mukgen/domain/review/service/ReviewService.java
  src/main/java/com/example/mukgen/domain/user/controller/UserController.java
Labels: 생성

#42 🔀 :: feature/lunch-board to develop
  src/main/java/com/example/mukgen/domain/mealsuggestion/controller/MealSuggestionController.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/controller/dto/request/MealSuggestionCreateRequest.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/controller/dto/request/MealSuggestionUpdateRequest.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/controller/dto/response/MealSuggestionMaximumResponse.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/controller/dto/response/MealSuggestionMinimumResponse.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/entity/MealSuggestion.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/repository/MealSuggestionRepository.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/service/MealSuggestionService.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/service/exception/MealSuggestionNotFoundException.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/service/exception/MealSuggestionWriterMissMatchException.java
  src/main/java/com/example/mukgen/domain/mealsuggestionlike/controller/MealSuggestionLikeController.java
  src/main/java/com/example/mukgen/domain/mealsuggestionlike/controller/dto/request/MealSuggestionLikeRequest.java
  src/main/java/com/example/mukgen/domain/mealsuggestionlike/controller/dto/response/MealSuggestionLikeResponse.java
  src/main/java/com/example/mukgen/domain/mealsuggestionlike/entity/MealSuggestionLike.java
  src/main/java/com/example/mukgen/domain/mealsuggestionlike/repositery/MealSuggestionLikeRepository.java
  src/main/java/com/example/mukgen/domain/mealsuggestionlike/service/MealSuggestionLikeService.java
  src/main/java/com/example/mukgen/global/error/exception/ErrorCode.java
Labels: 생성

#68 🔀 :: feature/validation to develop
  src/main/java/com/example/mukgen/domain/auth/controller/request/UserSignupRequest.java
  src/main/java/com/example/mukgen/domain/board/controller/dto/request/BoardCreateRequest.java
  src/main/java/com/example/mukgen/domain/board/controller/dto/request/BoardUpdateRequest.java
  src/main/java/com/example/mukgen/domain/board/controller/dto/request/UserModifyPasswordRequest.java
  src/main/java/com/example/mukgen/domain/boardcomment/controller/dto/request/BoardCommentCreateRequest.java
  src/main/java/com/example/mukgen/domain/boardcomment/controller/dto/request/BoardCommentUpdateRequest.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/controller/dto/request/MealSuggestionCreateRequest.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/controller/dto/request/MealSuggestionUpdateRequest.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/controller/dto/response/MealSuggestionMaximumResponse.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/controller/dto/response/MealSuggestionMinimumResponse.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/entity/MealSuggestion.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/service/MealSuggestionService.java
  src/main/java/com/example/mukgen/domain/review/controller/dto/request/ReviewCreateRequest.java
Labels: 생성

#71 🔀 :: feature/validation to develop
  src/main/java/com/example/mukgen/domain/board/controller/BoardController.java
  src/main/java/com/example/mukgen/domain/boardcomment/controller/BoardCommentController.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/controller/MealSuggestionController.java
  src/main/java/com/example/mukgen/domain/review/controller/ReviewController.java
Labels: 리펙토링

#70 🔀 :: feature/mealsuggestioncheck to develop
  src/main/java/com/example/mukgen/domain/mealsuggestion/controller/MealSuggestionController.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/controller/dto/response/MealSuggestionMaximumResponse.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/controller/dto/response/MealSuggestionMinimumResponse.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/entity/MealSuggestion.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/service/MealSuggestionService.java
  src/main/java/com/example/mukgen/domain/user/service/exception/NoPermissionException.java
  src/main/java/com/example/mukgen/global/error/exception/ErrorCode.java
Labels: 생성

#72 🔀 :: feature/mealsuggestion to develop
  src/main/java/com/example/mukgen/domain/mealsuggestion/controller/MealSuggestionController.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/controller/dto/response/MealSuggestionMinimumResponse.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/controller/dto/response/MealSuggestionResponse.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/entity/MealSuggestion.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/service/MealSuggestionService.java
Labels: 삭제

#74 🔀 :: feature/base-time-entity to develop
  src/main/java/com/example/mukgen/domain/BaseTimeEntity.java
  src/main/java/com/example/mukgen/domain/board/controller/dto/response/BoardMaximumResponse.java
  src/main/java/com/example/mukgen/domain/board/controller/dto/response/BoardMinimumResponse.java
  src/main/java/com/example/mukgen/domain/board/entity/Board.java
  src/main/java/com/example/mukgen/domain/board/repository/BoardRepository.java
  src/main/java/com/example/mukgen/domain/board/service/BoardService.java
  src/main/java/com/example/mukgen/domain/boardcomment/controller/dto/response/BoardCommentResponse.java
  src/main/java/com/example/mukgen/domain/boardcomment/entity/BoardComment.java
  src/main/java/com/example/mukgen/domain/boardcomment/service/BoardCommentService.java
  src/main/java/com/example/mukgen/domain/like/entity/Likes.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/controller/dto/response/MealSuggestionResponse.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/entity/MealSuggestion.java
  src/main/java/com/example/mukgen/domain/mealsuggestionlike/entity/MealSuggestionLike.java
  src/main/java/com/example/mukgen/domain/review/entity/Review.java
Labels: 수정

#79 🔀 :: feature/delivery-party to develop
  src/main/java/com/example/mukgen/domain/deliveryparty/controller/DeliveryPartyController.java
  src/main/java/com/example/mukgen/domain/deliveryparty/controller/dto/request/DeliveryPartyRequest.java
  src/main/java/com/example/mukgen/domain/deliveryparty/controller/dto/response/DeliveryPartyListResponse.java
  src/main/java/com/example/mukgen/domain/deliveryparty/service/DeliveryPartyService.java
Labels: 수정

#81 🔀 :: feature/board to develop
  src/main/java/com/example/mukgen/domain/board/service/BoardService.java
  src/main/java/com/example/mukgen/domain/board/service/exception/BoardWriterMissMatchException.java
Labels: 버그

#80 🔀 :: feature/delivery-party to develop
  src/main/java/com/example/mukgen/domain/deliveryparty/controller/dto/response/DeliveryPartyListResponse.java
  src/main/java/com/example/mukgen/domain/deliveryparty/service/DeliveryPartyService.java
Labels: 리펙토링

#83 🔀 :: feature/review-comment develop
  src/main/java/com/example/mukgen/domain/review/controller/dto/response/ReviewMaximumResponse.java
  src/main/java/com/example/mukgen/domain/review/entity/Review.java
  src/main/java/com/example/mukgen/domain/review/service/ReviewService.java
  src/main/java/com/example/mukgen/domain/reviewcomment/controller/ReviewCommentController.java
  src/main/java/com/example/mukgen/domain/reviewcomment/controller/dto/request/ReviewCommentCreateRequest.java
  src/main/java/com/example/mukgen/domain/reviewcomment/controller/dto/request/ReviewCommentUpdateRequest.java
  src/main/java/com/example/mukgen/domain/reviewcomment/controller/dto/response/ReviewCommentListResponse.java
  src/main/java/com/example/mukgen/domain/reviewcomment/controller/dto/response/ReviewCommentResponse.java
  src/main/java/com/example/mukgen/domain/reviewcomment/entity/ReviewComment.java
  src/main/java/com/example/mukgen/domain/reviewcomment/repository/ReviewCommentRepository.java
  src/main/java/com/example/mukgen/domain/reviewcomment/service/ReviewCommentService.java
Labels: 생성

#85 🔀 :: feature/chef to develop
  src/main/java/com/example/mukgen/domain/auth/controller/AuthController.java
  src/main/java/com/example/mukgen/domain/auth/controller/request/ChefSignupRequest.java
  src/main/java/com/example/mukgen/domain/auth/service/AuthService.java
  src/main/java/com/example/mukgen/domain/auth/service/exception/CodeMismatchException.java
  src/main/java/com/example/mukgen/global/error/exception/ErrorCode.java
Labels: 생성

#92 🔀 :: feature/auth to develop
  src/main/java/com/example/mukgen/domain/auth/controller/request/UserSignupRequest.java
  src/main/java/com/example/mukgen/domain/auth/service/AuthService.java
  src/main/java/com/example/mukgen/domain/auth/service/exception/PassWordCheckMismatchException.java
  src/main/java/com/example/mukgen/global/error/exception/ErrorCode.java
Labels: 생성

#94 🔀 :: feature/delivery-party to develop
  src/main/java/com/example/mukgen/domain/deliveryparty/controller/DeliveryPartyController.java
  src/main/java/com/example/mukgen/domain/deliveryparty/entity/DeliveryParty.java
  src/main/java/com/example/mukgen/domain/deliveryparty/repository/DeliveryPartyRepository.java
  src/main/java/com/example/mukgen/domain/deliveryparty/service/DeliveryPartyService.java
  src/main/java/com/example/mukgen/domain/deliveryparty/service/exception/DeliveryPartyMeetTimeException.java
  src/main/java/com/example/mukgen/domain/deliveryparty/service/exception/DeliveryPartyNotJoinException.java
  src/main/java/com/example/mukgen/global/error/exception/ErrorCode.java
Labels: 생성

#96 🔀 :: feature/mealSuggestion to develop
  src/main/java/com/example/mukgen/domain/mealsuggestion/controller/MealSuggestionController.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/controller/MealSuggestionLikeController.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/controller/dto/request/MealSuggestionLikeRequest.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/controller/dto/response/MealSuggestionLikeResponse.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/controller/dto/response/MealSuggestionResponse.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/entity/MealSuggestion.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/entity/MealSuggestionLike.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/repository/MealSuggestionLikeRepository.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/service/MealSuggestionLikeService.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/service/MealSuggestionService.java
Labels: 생성

#98 🔀 :: feature/paging to develop
  src/main/java/com/example/mukgen/domain/board/controller/BoardController.java
  src/main/java/com/example/mukgen/domain/board/repository/BoardRepository.java
  src/main/java/com/example/mukgen/domain/board/service/BoardService.java
  src/main/java/com/example/mukgen/domain/user/controller/UserController.java
Labels: 생성

#100 🔀 :: develop/delivery-party to develop
  src/main/java/com/example/mukgen/domain/deliveryparty/service/DeliveryPartyService.java
  src/main/java/com/example/mukgen/domain/user/entity/User.java
Labels: 버그

#102 🔀 :: feature/refactoring to develop
  src/main/java/com/example/mukgen/domain/review/controller/ReviewController.java
  src/main/java/com/example/mukgen/domain/review/controller/dto/response/ReviewListResponse.java
  src/main/java/com/example/mukgen/domain/review/controller/dto/response/ReviewRankListResponse.java
  src/main/java/com/example/mukgen/domain/review/controller/dto/response/ReviewTodayListResponse.java
  src/main/java/com/example/mukgen/domain/review/service/ReviewService.java
  src/main/java/com/example/mukgen/domain/user/controller/UserController.java
Labels: 리펙토링

#110 🔀 :: feature/rice to develop
  src/main/java/com/example/mukgen/domain/rice/controller/dto/response/RiceResponse.java
  src/main/java/com/example/mukgen/domain/rice/service/RiceService.java
Labels: 생성

#108 🔀 :: feture/mealsuggestion to develop
  src/main/java/com/example/mukgen/domain/mealsuggestion/repository/MealSuggestionRepository.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/service/MealSuggestionScheduledService.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/service/MealSuggestionService.java
Labels: 생성

#113 🔀 :: feature/delivery-party to develop
  src/main/java/com/example/mukgen/domain/deliveryparty/controller/DeliveryPartyController.java
  src/main/java/com/example/mukgen/domain/deliveryparty/entity/DeliveryParty.java
  src/main/java/com/example/mukgen/domain/deliveryparty/service/DeliveryPartyService.java
  src/main/java/com/example/mukgen/domain/user/entity/User.java
Labels: 리펙토링

#114 🔀 :: feature/rice to develop
  src/main/java/com/example/mukgen/domain/rice/controller/dto/response/RiceResponse.java
  src/main/java/com/example/mukgen/domain/rice/entity/RiceType.java
  src/main/java/com/example/mukgen/domain/rice/service/RiceApi.java
  src/main/java/com/example/mukgen/domain/rice/service/RiceService.java
Labels: 버그

#115 🔀 :: feature/delivery-party to develop
  src/main/java/com/example/mukgen/domain/deliveryparty/service/DeliveryPartyService.java
  src/main/java/com/example/mukgen/domain/deliveryparty/service/exception/DeliveryPartyCantLeaveException.java
  src/main/java/com/example/mukgen/global/error/exception/ErrorCode.java
Labels: 생성

#117 🔀 :: feature/rice to develop
  src/main/java/com/example/mukgen/domain/rice/service/RiceService.java
Labels: 버그

#119 🔀 :: feature/review to develop
  src/main/java/com/example/mukgen/domain/review/service/ReviewService.java
  src/main/java/com/example/mukgen/domain/review/service/exception/ReviewYetTimeException.java
  src/main/java/com/example/mukgen/global/error/exception/ErrorCode.java
Labels: 생성

#121 🔀 :: feature/refactoring to develop
  src/main/java/com/example/mukgen/global/error/exception/ErrorCode.java
Labels: 리펙토링

#122 🔀 :: repactoring to develop
  src/main/java/com/example/mukgen/domain/mealsuggestion/controller/MealSuggestionController.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/controller/dto/response/MealSuggestionListResponse.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/controller/dto/response/MealSuggestionResponse.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/service/MealSuggestionService.java
Labels: 리펙토링

#124 🔀 :: develop to main
  .github/workflows/gradle.yml
Labels: 합병

#125 🔀 :: develop to main
  .github/workflows/gradle.yml
Labels: 합병

#128 🔀 :: feature/rice to develop
  src/main/java/com/example/mukgen/domain/rice/controller/RiceController.java
  src/main/java/com/example/mukgen/domain/rice/service/RiceScheduledService.java
  src/main/java/com/example/mukgen/domain/rice/service/RiceService.java
Labels: 생성

#129 🔀 :: develop to main
  src/main/java/com/example/mukgen/domain/rice/controller/RiceController.java
  src/main/java/com/example/mukgen/domain/rice/service/RiceScheduledService.java
  src/main/java/com/example/mukgen/domain/rice/service/RiceService.java
Labels: 생성

#131 🔀 :: feature/rice to develop
  src/main/java/com/example/mukgen/domain/rice/service/RiceService.java
Labels: 수정

#132 🔀 :: develop to main
  src/main/java/com/example/mukgen/domain/rice/service/RiceService.java
Labels: 수정

#133 🔀 :: feature/rice to develop
  src/main/java/com/example/mukgen/domain/rice/service/RiceService.java
Labels: 버그

#134 🔀 :: develop to main
  src/main/java/com/example/mukgen/domain/rice/service/RiceService.java
Labels: 버그

#138 🔀 :: develop to main
  src/main/java/com/example/mukgen/MukgenApplication.java
  src/main/java/com/example/mukgen/domain/auth/controller/AuthController.java
  src/main/java/com/example/mukgen/domain/auth/controller/reponse/TokenResponse.java
  src/main/java/com/example/mukgen/domain/auth/entity/RefreshToken.java
  src/main/java/com/example/mukgen/domain/auth/repository/RefreshTokenRepository.java
  src/main/java/com/example/mukgen/domain/auth/service/AuthService.java
  src/main/java/com/example/mukgen/global/config/redis/RedisConfig.java
  src/main/java/com/example/mukgen/global/config/redis/property/RedisProperty.java
  src/main/java/com/example/mukgen/global/config/security/SecurityConfig.java
  src/main/java/com/example/mukgen/global/config/security/auth/CustomUserDetailService.java
  src/main/java/com/example/mukgen/global/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/mukgen/global/config/security/jwt/JwtTokenProvider.java
  src/main/java/com/example/mukgen/global/error/exception/ErrorCode.java
  src/main/java/com/example/mukgen/global/error/exception/ExpiredTokenException.java
  src/main/java/com/example/mukgen/global/error/exception/InvalidTokenException.java
Labels: 생성

#139 🔀 :: feature/refresh-token to develop
  src/main/java/com/example/mukgen/domain/auth/controller/AuthController.java
  src/main/java/com/example/mukgen/domain/auth/controller/request/ReIssueRequest.java
  src/main/java/com/example/mukgen/global/config/redis/RedisConfig.java
  src/main/java/com/example/mukgen/global/config/redis/property/RedisProperty.java
  src/main/java/com/example/mukgen/global/config/security/SecurityConfig.java
  src/main/java/com/example/mukgen/global/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/mukgen/global/config/security/jwt/JwtTokenProvider.java
Labels: 생성

#140 🔀 :: develop to main
  .github/workflows/gradle.yml
  src/main/java/com/example/mukgen/domain/auth/controller/AuthController.java
  src/main/java/com/example/mukgen/domain/auth/controller/request/ReIssueRequest.java
  src/main/java/com/example/mukgen/global/config/redis/RedisConfig.java
  src/main/java/com/example/mukgen/global/config/redis/property/RedisProperty.java
  src/main/java/com/example/mukgen/global/config/security/SecurityConfig.java
  src/main/java/com/example/mukgen/global/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/mukgen/global/config/security/jwt/JwtTokenProvider.java
Labels: 생성, 합병

#141 🔀 :: devleop to main
  src/main/java/com/example/mukgen/global/config/security/jwt/JwtTokenProvider.java
Labels: 합병

#142 🔀 :: devleop to main
  src/main/java/com/example/mukgen/global/config/security/SecurityConfig.java
Labels: 합병

#143 🔀 :: devleop to main
  src/main/java/com/example/mukgen/global/config/security/jwt/JwtFilter.java
  src/main/java/com/example/mukgen/global/config/security/jwt/JwtProperties.java
  src/main/java/com/example/mukgen/global/config/security/jwt/JwtTokenProvider.java
  src/main/resources/application.yml
Labels: 합병

#144 🔀 :: devleop to main
  src/main/java/com/example/mukgen/global/config/security/jwt/JwtProperties.java
  src/main/resources/application.yml
Labels: 합병

#145 🔀 :: devleop to main
  src/main/java/com/example/mukgen/global/config/security/jwt/JwtProperties.java
Labels: 합병

#146 🔀 :: devleop to main
  src/main/java/com/example/mukgen/global/config/security/SecurityConfig.java
Labels: 합병

#147 🔀 :: devleop to main
  src/main/java/com/example/mukgen/global/config/security/SecurityConfig.java
  src/main/java/com/example/mukgen/global/config/security/jwt/JwtFilter.java
  src/main/java/com/example/mukgen/global/config/security/jwt/JwtTokenProvider.java
Labels: 합병

#148 🔀 :: devleop to main
  src/main/java/com/example/mukgen/global/config/FilterConfig.java
  src/main/java/com/example/mukgen/global/config/security/jwt/JwtFilter.java
Labels: 합병

#149 🔀 :: devleop to main
  src/main/java/com/example/mukgen/global/config/security/SecurityConfig.java
  src/main/java/com/example/mukgen/global/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/mukgen/global/config/security/jwt/JwtTokenProvider.java
Labels: 합병

#150 🔀 :: devleop to main
  src/main/java/com/example/mukgen/global/config/security/SecurityConfig.java
  src/main/java/com/example/mukgen/global/config/security/jwt/JwtAuthenticationFilter.java
Labels: 합병

#151 🔀 :: devleop to main
  src/main/java/com/example/mukgen/global/config/FilterConfig.java
  src/main/java/com/example/mukgen/global/config/security/SecurityConfig.java
  src/main/java/com/example/mukgen/global/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/mukgen/global/config/security/jwt/JwtFilter.java
  src/main/java/com/example/mukgen/global/config/security/jwt/JwtTokenProvider.java
Labels: 합병

#152 🔀 :: devleop to main
  src/main/java/com/example/mukgen/global/config/security/jwt/JwtProperties.java
  src/main/java/com/example/mukgen/global/config/security/jwt/JwtTokenProvider.java
  src/main/resources/application.yml
Labels: 합병

#153 🔀 :: devleop to main
  src/main/java/com/example/mukgen/global/config/security/jwt/JwtTokenProvider.java
Labels: 합병

#155 🔀 :: develop to main
  build.gradle.kts
  src/main/java/com/example/mukgen/domain/user/controller/UserController.java
  src/main/java/com/example/mukgen/infra/s3/config/AwsConfig.java
  src/main/java/com/example/mukgen/infra/s3/service/S3Service.java
  src/main/resources/application.yml
Labels: 생성, 합병

#156 🔀 :: feature/s3-image to develop
  src/main/java/com/example/mukgen/domain/user/controller/UserController.java
  src/main/java/com/example/mukgen/domain/user/controller/response/UserInfoResponse.java
  src/main/java/com/example/mukgen/domain/user/entity/User.java
  src/main/java/com/example/mukgen/domain/user/service/UserService.java
  src/main/java/com/example/mukgen/infra/s3/service/S3Service.java
  src/main/java/com/example/mukgen/infra/s3/service/S3Util.java
  src/main/resources/application.yml
Labels: 생성

#157 🔀 :: develop to main
  src/main/java/com/example/mukgen/domain/user/controller/UserController.java
  src/main/java/com/example/mukgen/domain/user/controller/response/UserInfoResponse.java
  src/main/java/com/example/mukgen/domain/user/entity/User.java
  src/main/java/com/example/mukgen/domain/user/service/UserService.java
  src/main/java/com/example/mukgen/infra/s3/service/S3Service.java
  src/main/java/com/example/mukgen/infra/s3/service/S3Util.java
  src/main/resources/application.yml
Labels: 생성

#158 🔀 :: feature/s3-image to develop
  src/main/java/com/example/mukgen/domain/user/service/UserService.java
Labels: 버그

#159 🔀 :: develop to main
  src/main/java/com/example/mukgen/domain/user/service/UserService.java
Labels: 버그
