Repository mukgen/mukgen_BackEnd_V1, pull requests merged in 2023-07, with the labels that each got.

#210 🔀 :: develop to main
  src/main/java/com/example/mukgen/domain/rice/service/RiceService.java
Labels: 버그, 합병

#211 🔀 :: develop to main
  src/main/resources/application.yml
Labels: 합병

#214 🔀 :: feature/meal-suggestion to develop
  src/main/java/com/example/mukgen/domain/mealsuggestion/controller/MealSuggestionController.java
Labels: 리펙토링

#216 🔀 :: feature/meal-suggestion to develop
  src/main/java/com/example/mukgen/domain/mealsuggestion/controller/dto/request/MealSuggestionCreateRequest.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/controller/dto/request/MealSuggestionUpdateRequest.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/entity/MealSuggestion.java
Labels: 리펙토링

#217 🔀 :: feature/mail to develop
  build.gradle.kts
  src/main/java/com/example/mukgen/domain/auth/controller/request/UserSignupRequest.java
  src/main/java/com/example/mukgen/domain/auth/service/AuthService.java
  src/main/java/com/example/mukgen/domain/auth/service/exception/InvalidMailException.java
  src/main/java/com/example/mukgen/domain/mail/controller/MailController.java
  src/main/java/com/example/mukgen/domain/mail/controller/dto/request/AuthenticateMailRequest.java
  src/main/java/com/example/mukgen/domain/mail/controller/dto/request/SendMailRequest.java
  src/main/java/com/example/mukgen/domain/mail/entity/AuthenticatedMail.java
  src/main/java/com/example/mukgen/domain/mail/entity/Code.java
  src/main/java/com/example/mukgen/domain/mail/repository/AuthenticatedMailRepository.java
  src/main/java/com/example/mukgen/domain/mail/repository/CodeRepository.java
  src/main/java/com/example/mukgen/domain/mail/service/MailService.java
  src/main/java/com/example/mukgen/domain/mail/service/exception/UnAuthenticatedMailException.java
  src/main/java/com/example/mukgen/domain/user/entity/User.java
  src/main/java/com/example/mukgen/domain/user/repository/UserRepository.java
  src/main/java/com/example/mukgen/global/config/security/SecurityConfig.java
  src/main/java/com/example/mukgen/global/error/exception/ErrorCode.java
  src/main/java/com/example/mukgen/infra/mail/MailUtil.java
  src/main/resources/application.yml
Labels: 생성

#218 🔀 :: feature/mail to develop
  src/main/java/com/example/mukgen/infra/mail/MailUtil.java
Labels: 리펙토링
