Repository mukgen/mukgen_BackEnd_V1, pull requests merged in 2023-06, with the labels that each got.

#160 🔀 :: feature/review-image to develop
  src/main/java/com/example/mukgen/domain/review/controller/ReviewController.java
  src/main/java/com/example/mukgen/domain/review/entity/Review.java
  src/main/java/com/example/mukgen/domain/review/service/ReviewService.java
  src/main/java/com/example/mukgen/domain/review/service/exception/ReviewWriterMismatchException.java
Labels: 생성

#161 🔀 :: develop to main
  src/main/java/com/example/mukgen/domain/review/controller/ReviewController.java
  src/main/java/com/example/mukgen/domain/review/entity/Review.java
  src/main/java/com/example/mukgen/domain/review/service/ReviewService.java
  src/main/java/com/example/mukgen/domain/review/service/exception/ReviewWriterMismatchException.java
Labels: 생성

#167 🔀 :: feature/auth to develop
  src/main/java/com/example/mukgen/domain/auth/service/AuthService.java
  src/main/java/com/example/mukgen/domain/rice/controller/dto/response/MukgenPickResponse.java
  src/main/java/com/example/mukgen/domain/rice/entity/MukgenPick.java
  src/main/java/com/example/mukgen/domain/rice/repository/MukgenPickRepository.java
  src/main/java/com/example/mukgen/domain/rice/service/RiceService.java
  src/main/java/com/example/mukgen/domain/rice/service/exception/MukgenPickNotFoundException.java
  src/main/java/com/example/mukgen/global/error/exception/ErrorCode.java
Labels: 리펙토링

#169 🔀 :: feature/mukgen-pick to develop
  src/main/java/com/example/mukgen/domain/rice/controller/RiceController.java
  src/main/java/com/example/mukgen/domain/rice/controller/dto/request/MukgenPickRequest.java
  src/main/java/com/example/mukgen/domain/rice/controller/dto/response/MukgenPickResponse.java
  src/main/java/com/example/mukgen/domain/rice/entity/MukgenPick.java
  src/main/java/com/example/mukgen/domain/rice/service/RiceService.java
Labels: 생성

#170 🔀 :: develop to main
  src/main/java/com/example/mukgen/domain/rice/controller/RiceController.java
  src/main/java/com/example/mukgen/domain/rice/controller/dto/request/MukgenPickRequest.java
  src/main/java/com/example/mukgen/domain/rice/controller/dto/response/MukgenPickResponse.java
  src/main/java/com/example/mukgen/domain/rice/entity/MukgenPick.java
  src/main/java/com/example/mukgen/domain/rice/service/RiceService.java
Labels: 생성, 합병

#171 🔀 :: feature/review-image to develop
  src/main/java/com/example/mukgen/domain/review/controller/ReviewController.java
  src/main/java/com/example/mukgen/domain/review/service/ReviewService.java
Labels: 생성

#172 🔀 :: develop to main
  .github/workflows/gradle.yml
  src/main/java/com/example/mukgen/domain/review/controller/ReviewController.java
  src/main/java/com/example/mukgen/domain/review/service/ReviewService.java
Labels: 합병

#174 🔀 :: feature/s3-util to develop
  src/main/java/com/example/mukgen/infra/s3/service/S3Util.java
Labels: 수정

#175 🔀 :: develop to main
  src/main/java/com/example/mukgen/infra/s3/service/S3Util.java
Labels: 합병

#173 🔀 :: repactoring to main
  src/main/java/com/example/mukgen/domain/auth/controller/AuthController.java
  src/main/java/com/example/mukgen/domain/auth/controller/response/LoginResponse.java
  src/main/java/com/example/mukgen/domain/auth/controller/response/TokenResponse.java
  src/main/java/com/example/mukgen/domain/auth/service/AuthService.java
  src/main/java/com/example/mukgen/global/config/security/jwt/JwtTokenProvider.java
Labels: 리펙토링

#177 🔀 :: feature/auth to develop
  src/main/java/com/example/mukgen/domain/auth/controller/AuthController.java
  src/main/java/com/example/mukgen/domain/auth/controller/request/ChefSignupRequest.java
  src/main/java/com/example/mukgen/domain/auth/controller/request/ReIssueRequest.java
  src/main/java/com/example/mukgen/domain/auth/controller/request/UserLoginRequest.java
  src/main/java/com/example/mukgen/domain/auth/controller/request/UserSignupRequest.java
  src/main/java/com/example/mukgen/domain/auth/controller/response/LoginResponse.java
  src/main/java/com/example/mukgen/domain/auth/controller/response/TokenResponse.java
  src/main/java/com/example/mukgen/domain/auth/entity/RefreshToken.java
  src/main/java/com/example/mukgen/domain/auth/service/AuthService.java
  src/main/java/com/example/mukgen/domain/board/controller/BoardController.java
  src/main/java/com/example/mukgen/domain/board/controller/LikesController.java
  src/main/java/com/example/mukgen/domain/board/entity/Board.java
  src/main/java/com/example/mukgen/domain/board/entity/BoardComment.java
  src/main/java/com/example/mukgen/domain/board/entity/Likes.java
  src/main/java/com/example/mukgen/domain/board/service/BoardCommentService.java
  src/main/java/com/example/mukgen/domain/board/service/BoardService.java
  src/main/java/com/example/mukgen/domain/board/service/LikeService.java
  src/main/java/com/example/mukgen/domain/deliveryparty/controller/DeliveryPartyController.java
  src/main/java/com/example/mukgen/domain/deliveryparty/controller/dto/request/DeliveryPartyRequest.java
  src/main/java/com/example/mukgen/domain/deliveryparty/controller/dto/response/DeliveryPartyResponse.java
  src/main/java/com/example/mukgen/domain/deliveryparty/entity/DeliveryParty.java
  src/main/java/com/example/mukgen/domain/deliveryparty/service/DeliveryPartyScheduledService.java
  src/main/java/com/example/mukgen/domain/deliveryparty/service/DeliveryPartyService.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/controller/MealSuggestionController.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/entity/MealSuggestion.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/service/MealSuggestionScheduledService.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/service/MealSuggestionService.java
  src/main/java/com/example/mukgen/domain/review/controller/ReviewCommentController.java
  src/main/java/com/example/mukgen/domain/review/controller/ReviewController.java
  src/main/java/com/example/mukgen/domain/review/controller/dto/response/ReviewListResponse.java
  src/main/java/com/example/mukgen/domain/review/entity/Review.java
  src/main/java/com/example/mukgen/domain/review/entity/ReviewComment.java
  src/main/java/com/example/mukgen/domain/review/service/ReviewCommentService.java
  src/main/java/com/example/mukgen/domain/review/service/ReviewService.java
  src/main/java/com/example/mukgen/domain/rice/controller/RiceController.java
  src/main/java/com/example/mukgen/domain/rice/service/RiceScheduledService.java
  src/main/java/com/example/mukgen/domain/rice/service/RiceService.java
  src/main/java/com/example/mukgen/domain/user/controller/UserController.java
  src/main/java/com/example/mukgen/domain/user/entity/User.java
  src/main/java/com/example/mukgen/domain/user/service/UserFacade.java
  src/main/java/com/example/mukgen/domain/user/service/UserService.java
  src/main/java/com/example/mukgen/global/config/FilterConfig.java
  src/main/java/com/example/mukgen/global/config/security/SecurityConfig.java
  src/main/java/com/example/mukgen/global/config/security/auth/CustomUserDetailService.java
  src/main/java/com/example/mukgen/global/config/security/auth/CustomUserDetails.java
  src/main/java/com/example/mukgen/global/config/security/jwt/JwtTokenProvider.java
  src/main/java/com/example/mukgen/global/error/GlobalExceptionFilter.java
Labels: 생성

#178 🔀 :: develop to main
  src/main/java/com/example/mukgen/domain/auth/controller/AuthController.java
  src/main/java/com/example/mukgen/domain/auth/service/AuthService.java
  src/main/java/com/example/mukgen/domain/user/entity/User.java
Labels: 합병

#180 🔀 :: feature/popular-post to develop
  src/main/java/com/example/mukgen/domain/board/repository/BoardRepository.java
  src/main/java/com/example/mukgen/domain/board/service/BoardService.java
Labels: 생성

#182 🔀 :: feature/auth to main
  src/main/java/com/example/mukgen/domain/auth/controller/request/UserModifyPasswordRequest.java
  src/main/java/com/example/mukgen/domain/auth/service/AuthService.java
  src/main/java/com/example/mukgen/domain/auth/service/exception/PasswordSameException.java
Labels: 생성

#184 🔀 :: bug/delivery-party to develop
  src/main/java/com/example/mukgen/domain/deliveryparty/service/DeliveryPartyScheduledService.java
  src/main/java/com/example/mukgen/domain/user/repository/UserRepository.java
Labels: 버그

#185 🔀 :: develop to main
  src/main/java/com/example/mukgen/MukgenApplication.java
  src/main/java/com/example/mukgen/domain/board/entity/Likes.java
  src/main/java/com/example/mukgen/domain/deliveryparty/service/DeliveryPartyScheduledService.java
  src/main/java/com/example/mukgen/domain/user/repository/UserRepository.java
  src/main/resources/application.yml
Labels: 버그

#186 🔀 :: develop to main
  src/main/java/com/example/mukgen/domain/deliveryparty/service/DeliveryPartyService.java
Labels: 버그

#187 🔀 :: develop to main
  src/main/java/com/example/mukgen/domain/deliveryparty/service/DeliveryPartyService.java
Labels: 버그

#190 🔀 :: feature/info-oauth2 to develop
  build.gradle.kts
  src/main/java/com/example/mukgen/domain/auth/controller/AuthController.java
  src/main/java/com/example/mukgen/domain/auth/controller/request/CodeRequest.java
  src/main/java/com/example/mukgen/domain/auth/service/AuthService.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/service/MealSuggestionService.java
  src/main/java/com/example/mukgen/domain/review/service/ReviewCommentService.java
  src/main/java/com/example/mukgen/domain/user/controller/response/UserInfoResponse.java
  src/main/java/com/example/mukgen/domain/user/controller/response/UserProfileResponse.java
  src/main/java/com/example/mukgen/domain/user/entity/User.java
  src/main/java/com/example/mukgen/domain/user/entity/type/UserRole.java
  src/main/java/com/example/mukgen/domain/user/repository/UserRepository.java
  src/main/java/com/example/mukgen/global/config/properties/InfoOAuthProperties.java
  src/main/java/com/example/mukgen/global/config/security/auth/CustomUserDetails.java
  src/main/java/oauth2/InfoOAuth2.java
  src/main/java/oauth2/dto/request/ExchangeTokenRequest.java
  src/main/java/oauth2/dto/response/ResourceResponse.java
  src/main/java/oauth2/dto/response/Role.java
  src/main/java/oauth2/dto/response/StudentResponse.java
  src/main/java/oauth2/dto/response/TeacherResponse.java
  src/main/java/oauth2/dto/response/TokenResponse.java
  src/main/java/oauth2/dto/response/UserResponse.java
  src/main/java/oauth2/exception/InfoOAuth2Exception.java
  src/main/java/oauth2/feign/BasicAuthInterceptor.java
  src/main/java/oauth2/feign/BearerAuthInterceptor.java
  src/main/java/oauth2/feign/InfoOAuth2Server.java
  src/main/resources/application.yml
Labels: 생성

#191 🔀 :: develop to main
  build.gradle.kts
  src/main/java/com/example/mukgen/domain/auth/controller/AuthController.java
  src/main/java/com/example/mukgen/domain/auth/controller/request/CodeRequest.java
  src/main/java/com/example/mukgen/domain/auth/service/AuthService.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/service/MealSuggestionService.java
  src/main/java/com/example/mukgen/domain/review/service/ReviewCommentService.java
  src/main/java/com/example/mukgen/domain/user/controller/response/UserInfoResponse.java
  src/main/java/com/example/mukgen/domain/user/controller/response/UserProfileResponse.java
  src/main/java/com/example/mukgen/domain/user/entity/User.java
  src/main/java/com/example/mukgen/domain/user/entity/type/UserRole.java
  src/main/java/com/example/mukgen/domain/user/repository/UserRepository.java
  src/main/java/com/example/mukgen/global/config/properties/InfoOAuthProperties.java
  src/main/java/com/example/mukgen/global/config/security/auth/CustomUserDetails.java
  src/main/java/oauth2/InfoOAuth2.java
  src/main/java/oauth2/dto/request/ExchangeTokenRequest.java
  src/main/java/oauth2/dto/response/ResourceResponse.java
  src/main/java/oauth2/dto/response/Role.java
  src/main/java/oauth2/dto/response/StudentResponse.java
  src/main/java/oauth2/dto/response/TeacherResponse.java
  src/main/java/oauth2/dto/response/TokenResponse.java
  src/main/java/oauth2/dto/response/UserResponse.java
  src/main/java/oauth2/exception/InfoOAuth2Exception.java
  src/main/java/oauth2/feign/BasicAuthInterceptor.java
  src/main/java/oauth2/feign/BearerAuthInterceptor.java
  src/main/java/oauth2/feign/InfoOAuth2Server.java
  src/main/resources/application.yml
Labels: 생성, 합병

#192 🔀 :: develop to main
  src/main/java/com/example/mukgen/domain/auth/controller/AuthController.java
  src/main/java/com/example/mukgen/domain/auth/service/AuthService.java
  src/main/java/com/example/mukgen/domain/user/entity/User.java
Labels: 생성, 합병

#193 🔀 :: develop to main
  src/main/java/com/example/mukgen/domain/auth/controller/AuthController.java
Labels: 생성, 합병

#196 🔀 :: feature/refactoring to develop
  src/main/java/com/example/mukgen/domain/board/controller/LikeController.java
  src/main/java/com/example/mukgen/domain/board/controller/dto/response/BoardMaximumResponse.java
  src/main/java/com/example/mukgen/domain/board/entity/Board.java
  src/main/java/com/example/mukgen/domain/board/entity/Like.java
  src/main/java/com/example/mukgen/domain/board/repository/LikeRepository.java
  src/main/java/com/example/mukgen/domain/board/service/BoardCommentService.java
  src/main/java/com/example/mukgen/domain/board/service/BoardService.java
  src/main/java/com/example/mukgen/domain/board/service/LikeService.java
  src/main/java/com/example/mukgen/domain/board/service/exception/BoardCommentWriterMissmatchException.java
  src/main/java/com/example/mukgen/domain/board/service/exception/BoardWriterMissmatchException.java
  src/main/java/com/example/mukgen/domain/deliveryparty/service/DeliveryPartyScheduledService.java
  src/main/java/com/example/mukgen/domain/deliveryparty/service/DeliveryPartyService.java
  src/main/java/com/example/mukgen/domain/deliveryparty/service/exception/DeliveryPartyAlreadyExistsException.java
  src/main/java/com/example/mukgen/domain/deliveryparty/service/exception/DeliveryPartyFullException.java
  src/main/java/com/example/mukgen/domain/deliveryparty/service/exception/DeliveryPartyInProgressException.java
  src/main/java/com/example/mukgen/domain/deliveryparty/service/exception/DeliveryPartyWriterMismatchException.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/entity/MealSuggestion.java
  src/main/java/com/example/mukgen/domain/rice/entity/MukgenPick.java
  src/main/java/com/example/mukgen/domain/rice/entity/Rice.java
  src/main/java/com/example/mukgen/domain/user/repository/UserRepository.java
  src/main/java/com/example/mukgen/global/config/security/jwt/JwtProperties.java
  src/main/java/com/example/mukgen/global/config/security/jwt/JwtResolver.java
  src/main/java/com/example/mukgen/global/config/security/jwt/JwtTokenProvider.java
  src/main/java/com/example/mukgen/global/exception/InvalidTokenException.java
  src/main/resources/application.yml
Labels: 리펙토링

#197 🔀 :: develop to main
  src/main/java/com/example/mukgen/domain/board/controller/LikeController.java
  src/main/java/com/example/mukgen/domain/board/controller/dto/response/BoardMaximumResponse.java
  src/main/java/com/example/mukgen/domain/board/entity/Board.java
  src/main/java/com/example/mukgen/domain/board/entity/Like.java
  src/main/java/com/example/mukgen/domain/board/repository/LikeRepository.java
  src/main/java/com/example/mukgen/domain/board/service/BoardCommentService.java
  src/main/java/com/example/mukgen/domain/board/service/BoardService.java
  src/main/java/com/example/mukgen/domain/board/service/LikeService.java
  src/main/java/com/example/mukgen/domain/board/service/exception/BoardCommentWriterMissmatchException.java
  src/main/java/com/example/mukgen/domain/board/service/exception/BoardWriterMissmatchException.java
  src/main/java/com/example/mukgen/domain/deliveryparty/service/DeliveryPartyScheduledService.java
  src/main/java/com/example/mukgen/domain/deliveryparty/service/DeliveryPartyService.java
  src/main/java/com/example/mukgen/domain/deliveryparty/service/exception/DeliveryPartyAlreadyExistsException.java
  src/main/java/com/example/mukgen/domain/deliveryparty/service/exception/DeliveryPartyFullException.java
  src/main/java/com/example/mukgen/domain/deliveryparty/service/exception/DeliveryPartyInProgressException.java
  src/main/java/com/example/mukgen/domain/deliveryparty/service/exception/DeliveryPartyWriterMismatchException.java
  src/main/java/com/example/mukgen/domain/mealsuggestion/entity/MealSuggestion.java
  src/main/java/com/example/mukgen/domain/rice/entity/MukgenPick.java
  src/main/java/com/example/mukgen/domain/rice/entity/Rice.java
  src/main/java/com/example/mukgen/domain/user/repository/UserRepository.java
  src/main/java/com/example/mukgen/global/config/security/jwt/JwtProperties.java
  src/main/java/com/example/mukgen/global/config/security/jwt/JwtResolver.java
  src/main/java/com/example/mukgen/global/config/security/jwt/JwtTokenProvider.java
  src/main/java/com/example/mukgen/global/exception/InvalidTokenException.java
  src/main/resources/application.yml
Labels: 리펙토링, 합병

#198 🔀 :: feature/monitoring to develop
  build.gradle.kts
  src/main/resources/application.yml
Labels: 생성

#201 🔀 :: feature/feign-client to develop
  build.gradle.kts
  src/main/java/com/example/mukgen/MukgenApplication.java
  src/main/java/com/example/mukgen/domain/rice/controller/RiceController.java
  src/main/java/com/example/mukgen/domain/rice/entity/Rice.java
  src/main/java/com/example/mukgen/domain/rice/service/RiceApi.java
  src/main/java/com/example/mukgen/domain/rice/service/RiceService.java
  src/main/java/com/example/mukgen/infra/feign/client/Config.java
  src/main/java/com/example/mukgen/infra/feign/client/NeisFeignClient.java
  src/main/java/com/example/mukgen/infra/feign/client/NeisUtil.java
  src/main/java/com/example/mukgen/infra/feign/dto/DietDTO.java
  src/main/java/com/example/mukgen/infra/feign/dto/DietInfoList.java
Labels: 생성

#202 🔀 :: develop to main
  .github/workflows/gradle.yml
  build.gradle.kts
  src/main/java/com/example/mukgen/MukgenApplication.java
  src/main/java/com/example/mukgen/domain/rice/controller/RiceController.java
  src/main/java/com/example/mukgen/domain/rice/entity/Rice.java
  src/main/java/com/example/mukgen/domain/rice/service/RiceApi.java
  src/main/java/com/example/mukgen/domain/rice/service/RiceService.java
  src/main/java/com/example/mukgen/infra/feign/client/Config.java
  src/main/java/com/example/mukgen/infra/feign/client/NeisFeignClient.java
  src/main/java/com/example/mukgen/infra/feign/client/NeisUtil.java
  src/main/java/com/example/mukgen/infra/feign/dto/DietDTO.java
  src/main/java/com/example/mukgen/infra/feign/dto/DietInfoList.java
Labels: 생성, 합병

#204 🔀 :: develop to main
  src/main/java/com/example/mukgen/domain/rice/entity/Rice.java
  src/main/java/com/example/mukgen/domain/rice/service/RiceService.java
  src/main/java/com/example/mukgen/infra/feign/client/NeisUtil.java
Labels: 버그

#205 🔀 :: develop to main
  src/main/java/com/example/mukgen/infra/feign/dto/DietDTO.java
  src/main/java/com/example/mukgen/infra/feign/dto/DietInfoList.java
Labels: 리펙토링

#207 🔀 :: develop to main
  src/main/java/com/example/mukgen/domain/rice/controller/RiceController.java
  src/main/java/com/example/mukgen/domain/rice/controller/dto/response/RiceMonthListResponse.java
  src/main/java/com/example/mukgen/domain/rice/controller/dto/response/RiceResponse.java
  src/main/java/com/example/mukgen/domain/rice/entity/Rice.java
  src/main/java/com/example/mukgen/domain/rice/repository/RiceRepository.java
  src/main/java/com/example/mukgen/domain/rice/service/MukgenPickScheduledService.java
  src/main/java/com/example/mukgen/domain/rice/service/RiceService.java
  src/main/java/com/example/mukgen/infra/feign/gpt/GptFeignClient.java
  src/main/java/com/example/mukgen/infra/feign/gpt/GptFeignRequest.java
  src/main/java/com/example/mukgen/infra/feign/gpt/GptResponse.java
  src/main/java/com/example/mukgen/infra/feign/gpt/Message.java
  src/main/java/com/example/mukgen/infra/feign/rice/Config.java
  src/main/java/com/example/mukgen/infra/feign/rice/NeisFeignClient.java
  src/main/java/com/example/mukgen/infra/feign/rice/NeisUtil.java
Labels: 생성

#208 🔀 :: develop to main
  src/main/java/com/example/mukgen/infra/feign/gpt/GptConfig.java
  src/main/java/com/example/mukgen/infra/feign/gpt/GptFeignClient.java
  src/main/java/com/example/mukgen/infra/feign/gpt/GptProperty.java
  src/main/resources/application.yml
Labels: 생성

#209 🔀 :: develop to main
  src/main/java/com/example/mukgen/domain/rice/service/RiceService.java
Labels: 버그
